### ISSUE TITLE
How to use dragon oss to copy file from HDFS to OSS?

### ISSUE THREAD

**Issue by judechen** [quixey/dragon-oss#2]
Could you please provide sample code to copy file from HDFS to OSS?

**Comment by wisematthew** [comment]
from the command line:

`hdfs dfs -cp hdfs:///path/to/file oss://bucket/path/`

**Comment by judechen** [comment]
How to do it in java code?

**Comment by wisematthew** [comment]
Dragon is an implementation of the Hadoop Filesystem for OSS.  You can copy to/from oss the same way you access hdfs in Java.  Use the `oss` scheme instead of the `hdfs` scheme when specifying paths.

https://hadoop.apache.org/docs/current/api/org/apache/hadoop/fs/FileSystem.html
