### ISSUE TITLE
Where should I put the jar?

### ISSUE THREAD

**Issue by judechen** [quixey/dragon-oss#3]
My hadoop is CDH-4.5.0. Where I should I dragon-0.1.0.jar? I put the jars in /usr/lib/hadoop-hdfs/lib, and execute common: hdfs dfs -ls oss://xyz/. Error comes: ls: No FileSystem for scheme: oss

**Comment by wisematthew** [comment]
As long as the jar is on your hadoop classpath, hadoop will be able to find the jar.  `/usr/lib/hadoop-hdfs/lib` is probably on your classpath.

You also need to modify `core-site.xml` to specify which class implements the HDFS filesystem for the `oss://` scheme according to the [Readme](https://github.com/quixey/dragon-oss/blob/master/README.md)

The change to `core-site.xml` may require you to restart HDFS.
